# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_summernote.settings


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=django_summernote.settings.uploaded_filepath, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded'),
        ),
    ]
